
export const matches = [
  {
    id: 1,
    week: 1,
    matchNo: 1,
    homeTeam: "Arsenal FC",
    awayTeam: "Chelsea FC",
    homeScore: 0,
    awayScore: 0,
    status: "pending",
    isAvailable: true,
  },
  {
    id: 2,
    week: 1,
    matchNo: 2,
    homeTeam: "Manchester United",
    awayTeam: "Liverpool FC",
    homeScore: 0,
    awayScore: 0,
    status: "completed",
    isAvailable: true,
  },
  {
    id: 3,
    week: 2,
    matchNo: 3,
    homeTeam: "Manchester City",
    awayTeam: "Tottenham Hotspur",
    homeScore: 0,
    awayScore: 0,
    status: "pending",
    isAvailable: true,
  },
  {
    id: 4,
    week: 4,
    matchNo: 4,
    homeTeam: "Newcastle United",
    awayTeam: "Aston Villa",
    homeScore: 0,
    awayScore: 0,
    status: "pending",
    isAvailable: false,
  },
];


export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@doe.com",
    phone: "1234567890",
    isActive: true,
    isAdmin: true,
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "janedoe@mail.com",
    phone: "1234567890",
    isActive: false,
    isAdmin: false,
  },
  {
    id: 3,
    name: "Bill John",
    email: "billjohn@mail.com",
    phone: "1234567890",
    isActive: true,
    isAdmin: false,
  },
  {
    id: 4,
    name: "Rob Smith",
    email: "robsmith@mail.com",
    phone: "1234567890",
    isActive: true,
    isAdmin: false,
  },
  {
    id: 5,
    name: "William Joseph",
    email: "williamjoseph@mail.com",
    phone: "1234567890",
    isActive: true,
    isAdmin: false,
  },
  {
    id: 6,
    name: "John Wilsburgh",
    email: "johnwilsburgh@mail.com",
    phone: "1234567890",
    isActive: true,
    isAdmin: false,
  },
 
];